--- 
- 
  hosts: all
  name: "Shell Examples"
  tasks: 
    - 
      name: "Check Date with Shell command"
      shell: Set-NetFirewallProfile -DefaultInboundAction Block -DefaultOutboundAction Allow –NotifyOnListen True -AllowUnicastResponseToMulticast True –LogFileName %SystemRoot%\System32\LogFiles\Firewall\pfirewall.log
