- name: Enable firewall for Domain, Public and Private profiles
  hosts: windows
  roles:
    - windows-firewall
  win_firewall:
    state: enabled
    profiles:
    - Domain
    - Private
    - Public
  tags: enable_firewall
