--- 
- 
  become: true
  become_method: su
  hosts: all
  shell: |
      Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
      Set-NetFirewallProfile -DefaultInboundAction Block -DefaultOutboundAction Block –NotifyOnListen True -AllowUnicastResponseToMulticast True –LogFileName %SystemRoot%\System32\LogFiles\Firewall\pfirewall.log

