--- 
- 
  hosts: all
  name: "Shell Examples"
  tasks: 
    - 
      name: "Check Date with Shell command"
      shell: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
      args:
        chdir: $HOME
